enum SwitcherPersistenceKeys {
    static let pushList = "pushList_paths"
    static let pushListTitles = "pushList_titles"
    static let pushListSubtitles = "pushList_subtitles"
    static let pushListScheduledStarts = "pushList_scheduled_starts"
    static let pushListScheduledDurations = "pushList_scheduled_durations"
    static let bgmList = "bgmList_paths"
    static let bgmListCategories = "bgmList_categories"
    static let bgmListTitles = "bgmList_titles"
    static let wallpapers = "backgroundWallpapers_paths"
    static let activeWallpaper = "activeWallpaper_path"
    static let cornerLogo = "cornerLogo_path"
    static let cornerLogoPosition = "cornerLogo_position"
    static let audioStrategy = "audioStrategy"
    static let speakerMode = "speakerMode"
    static let bgmPlayMode = "bgmPlayMode"
    static let autoPlayNextVideoOnEnd = "autoPlayNextVideoOnEnd"
    static let autoAdvanceAtScheduledTime = "autoAdvanceAtScheduledTime"
    static let showAgendaTimeline = "showAgendaTimeline"
    static let consoleMode = "consoleMode"
    static let themeOverride = "themeOverride"
    static let lowerThirdPresets = "overlay.presets.lowerThird.json"
    static let countdownPresets = "overlay.presets.countdown.json"
    static let tickerPresets = "overlay.presets.ticker.json"
}
